
platform :ios,’8.0’

target 'PropertyManager' do

pod 'ReactiveCocoa', '~> 2.5'
pod 'CocoaLumberjack', '~> 2.3.0'
pod 'AFNetworking'
pod 'SDCycleScrollView'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'SDWebImage'
pod 'SDAutoLayout'
pod 'MLLabel'
pod 'CTAssetsPickerController'
pod "Qiniu", "~> 7.1"
pod 'HandyAutoLayout', '~> 1.0.0’

end

